travis:
  secure:
    BINSTAR_TOKEN: 9aQBgvvmNJbzPSDol/L+I51LeKp2cxNYREN4vxv6a2gTX1SRkfPlORaBw926lOMg6oR+DQVBy16A5pLxRHKydslXs6+lT6Dd+fMrUDESNfA2B/0W79mvPPbm8n1V71TkibL2L7Y95ORA2ptWEUHbyQq+c0nxrZ4eZ/QN8LYtgWx9fEMuCRrDaEwbx+st0iHcVQYqfsyVWKxo9TmI376JlaYO/sc0tnzHuNW+xTjYxAwLJf2/br7oM4rhM2K9kg2xo5ca8e3p/iM+WJlRYW++11VUssuvd4C1oE60m0sIo/yKiKJH042WF4nE4MvB3f7xqxszaop7cdYxpE3Sa6mMj3zsYonoIw92YZ5C+K1LVZqvcbHcWJiSnFESNOMHJhkKVZBHirmbSxbDkXUFR7k+7OiaIL5ZrpCv8o+jdERr0g+qnx6S/qxZPNyMGTjqv/VrGtxCbzNaSsDJ24jSShSFkPewkp8wn63AUUDsnGk4a9R4mghgbLLAKNEWgz/31yo7ErScj/xuMSRhmuQU7OgmkJVAXihU81hL+QtKxJwCjZrK5m7PC5uEi2CwUJR+IXX7+/35/qULJs+9xa0fi86FED3nOi/JyHXdokryubRj5wsPFG9NY7v+UBFB/5ySJJmtFcOFI5k6VEYHe5DUQFzNhW5yv7hbNHGPHS/1vVcrmic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
